apiVersion: v1
kind: Service
metadata:
  name: collabdocs-backend-service
  labels:
    app: collabdocs
    component: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: collabdocs
    component: backend
  type: ClusterIP
