apiVersion: v1
kind: Service
metadata:
  name: collabdocs-frontend-service
  labels:
    app: collabdocs
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: collabdocs
    component: frontend
  type: ClusterIP
